export const SANITIZATION_CONFIG_TOKEN = 'SANITIZATION_CONFIG';
export const NORMALIZATION_CONFIG_TOKEN = 'NORMALIZATION_CONFIG';
export const SANITIZATION_MODULE_CONFIG_TOKEN = 'SANITIZATION_MODULE_CONFIG';
export const SANITIZATION_OPTIONS_METADATA = 'sanitization:options';
export const NORMALIZATION_OPTIONS_METADATA = 'normalization:options';